### ISSUE TITLE
Breaks autocomplete all together

### ISSUE THREAD

**Issue by jcontonio** [loklaan/autocomplete-underdash#2]
Love having this in my initial testing but it breaks all other autocompletion for me on a base install of Atom 1.3.1. Will look into it over coming weeks to see if I spot anything.

**Comment by loklaan** [comment]
@jcontonio Thanks for opening an issue mate, I'll get around to fixing this eventually.

Although, if you have the time, drop into the [Provider API](https://github.com/atom/autocomplete-plus/wiki/Provider-API) to debug this issue. It most likely was me not understanding a config option or something menial. :stuck_out_tongue_winking_eye:
